### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by DavidPeicho** [DavidPeicho/davidpeicho.github.io#8]
* [x] - Migrate to Sapper & Svelte
* [x] - Use Pure Markdown for Project List
* [x] - Use MDsveX for article post
